### ISSUE TITLE
Using the code for Adidas NFT Collection - getting the below error

### ISSUE THREAD

**Issue by udaiparvatha** [a16z/nft-analyst-starter-pack#3]
I was trying to use this code for Adidas NFT Collection (0x28472a58A490c5e09A238847F66A68a47cC76f0f)

I get the below error

Process started for contract address: 0x28472a58A490c5e09A238847F66A68a47cC76f0f
Exporting token transfers...
Traceback (most recent call last):
  File "export_data.py", line 164, in <module>
    export_data()
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "export_data.py", line 88, in export_data
    export_token_transfers(
  File "/Users/viper/Documents/OneDrive/TellerFinance/nft-analyst-starter-pack/jobs/export_token_transfers.py", line 27, in export_token_transfers
    token_transfers = pd.read_csv(output)
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1231, in _make_engine
    return mapping[engine](f, **self.options)
  File "/Users/viper/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 551, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file`

**Comment by emlazzarin** [comment]
Unfortunately, the Adidas NFT contract is an ERC-1155 NFT and not an ERC-721. We'll investigate extending the NFT Analyst Starter Pack to support ERC-1155s. In the meantime, here's an article from [web3 University](https://www.web3.university/article/comparing-erc-721-to-erc-1155) that explains the difference. Thanks!
